// 狼人杀身份译名。一字版(lang)用于头像上的身份角标，二字版(lang2)用于查验结果/死亡公开等文字场合。
export default {
	lang: "狼",
	lang2: "狼人",
	langwang: "狼王",
	langwang2: "狼王",
	bailang: "白狼",
	bailang2: "白狼",
	yinlang: "隐",
	yinlang2: "隐狼",
	pingmin: "民",
	pingmin2: "平民",
	yvyanjia: "预",
	yvyanjia2: "预言家",
	nvwu: "巫",
	nvwu2: "女巫",
	lieren: "猎",
	lieren2: "猎人",
	jx_gudushaonv: "觉醒孤独少女",
	jx_gudushaonv2: "觉醒孤独少女",
	cai: "猜",
	cai2: "猜",
	hao: "好人",
	hao2: "好人",
	huai: "狼人",
	huai2: "狼人",
	_sw_dieSkill: "技能",
};
